import StyleDictionary from 'style-dictionary';
import type { Config, TransformedToken } from 'style-dictionary/types';

// Transform: convert token path to kebab-case SCSS variable name
// e.g. ['color', 'brand', 'primary'] → 'color-brand-primary'
StyleDictionary.registerTransform({
  name: 'ds/name/kebab',
  type: 'name',
  transform: (token: TransformedToken) =>
    token.path.join('-').toLowerCase().replace(/[^a-z0-9-]/g, '-'),
});

// Transform: append 'px' to dimension tokens that are raw numbers
StyleDictionary.registerTransform({
  name: 'ds/value/dimension',
  type: 'value',
  filter: (token: TransformedToken) => token.$type === 'dimension',
  transform: (token: TransformedToken) => {
    const val = token.$value ?? token.value;
    if (typeof val === 'number') return `${val}px`;
    return String(val);
  },
});

// Format: emit a SCSS file of $variable: value; declarations
StyleDictionary.registerFormat({
  name: 'ds/scss/variables',
  format: ({ dictionary }) => {
    const lines: string[] = [
      '// Auto-generated by style-dictionary — do not edit manually',
      '// Run `npm run build:tokens` to regenerate',
      '',
    ];

    // Group tokens by their top-level category
    const grouped: Record<string, TransformedToken[]> = {};
    for (const token of dictionary.allTokens) {
      const category = token.path[0] ?? 'other';
      (grouped[category] ??= []).push(token);
    }

    for (const [category, tokens] of Object.entries(grouped)) {
      lines.push(`// ${category}`);
      for (const token of tokens) {
        const value = token.value ?? token.$value;
        lines.push(`$${token.name}: ${value};`);
      }
      lines.push('');
    }

    return lines.join('\n');
  },
});

// Format: emit a SCSS map for color tokens
StyleDictionary.registerFormat({
  name: 'ds/scss/color-map',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (t) => t.$type === 'color' || t.path[0] === 'color'
    );
    const lines: string[] = [
      '// Auto-generated color map — do not edit manually',
      '',
      '$colors: (',
    ];
    for (const token of colorTokens) {
      const value = token.value ?? token.$value;
      lines.push(`  '${token.name}': ${value},`);
    }
    lines.push(');');
    return lines.join('\n');
  },
});

const config: Config = {
  source: ['src/tokens/base.json'],
  platforms: {
    scss: {
      transforms: ['ds/name/kebab', 'ds/value/dimension'],
      buildPath: 'src/styles/tokens/',
      files: [
        {
          destination: '_variables.scss',
          format: 'ds/scss/variables',
        },
        {
          destination: '_color-map.scss',
          format: 'ds/scss/color-map',
          filter: (token: TransformedToken) =>
            token.$type === 'color' || token.path[0] === 'color',
        },
      ],
    },
  },
};

export default config;
